### ISSUE TITLE
Prepare notes/summary in LaTeX about neural ODEs

### ISSUE THREAD

**Issue by migduroli** [migduroli/pineurodes#2]
@chanhuh-icl: After you have completed studying the [neural ODEs course](https://www.depthfirstlearning.com/2019/NeuralODEs), you need to prepare a brief summary document where you explain with your own words (keeping it brief) what you've learned, derivations you've struggled with, and any additional material you might've needed to understand the course. 

The idea is that once you have learnt this, you must be able to explain to us what you've learnt, so that we can discuss together next steps, and so on.

As always, if you find any problem with LaTeX you can't find the solution, don't hesitate to comment it here by writing a comment associated with this issue.

The structure of the summary should have:

- [ ] Introduction about neural ODEs
- [ ] Summary: Numerical solutions of ODEs
- [ ] Summary: ResNets
- [ ] Summary: Adjoint method
- [ ] Summary: Neural ODEs

Thanks!

**Comment by chanhuh-icl** [comment]
I need to submit 'Literature Review' to the department before 15th of February.
So I am thinking of submitting this note after I develop further.
What do you think?

**Comment by migduroli** [comment]
There is no actual deadline for these notes. It'd be good to keep steadily progressing on what you had prepared already (as you showed us a nice PDF the other day). Hence, focus on the Literature Review, for sure, but try and keep progressing on your notes. These will be useful for your final thesis.
